# Generated by Django 5.2 on 2025-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userinfo_image_userinfo_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
