# Generated by Django 5.2 on 2025-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userinfo_profile_image_userinfo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
